import matplotlib.pyplot as plt
from matplotlib.image import imread

def ai():

    while True:
        print('\033[96m'+"************************************************************************")
        print('\033[1m'+"\t\tWelcome to 'DSA & Intelligent Agent' Help Desk!!")
        print("************************************************************************"+'\033[0m')
        print('\033[96m'+'\nHelp needed in topics: '+'\033[0m')
        print('\033[96m'+"1."+'\033[95m'+" Search Algorithms: "+'\033[0m')
        print('\033[96m'+"2."+'\033[92m'+" Game Search Algorithms: "+'\033[0m')
        print('\033[96m'+"3."+'\033[93m'+" Intelligent Agents: "+'\033[0m')
        print('\033[96m'+"4."+'\033[91m'+" Exit"+'\033[0m')
        choice1 = int(input('\033[94m'+"\tEnter the choice number: "+'\033[0m'))

        if choice1 == 1:
            print('\033[95m'+"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"+'\033[0m')
            print('\033[95m'+'\033[1m'+"\t\t\t\t\tSearch Algorithms"+'\033[0m')
            print('\033[95m'+"++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"+'\033[0m')
            print('\033[95m'+"\tSelect Algorithms: ")
            print("\t1. Depth First search: ")
            print("\t2. Breadth First Search: ")
            print("\t3. Uniform Cost Search: ")
            print("\t4. Best First search: ")
            print("\t5. A* Search: ")
            print("\t6. Greedy Search: ")
            print("\t7. Exit"+'\033[0m')
            choice2 = int(input('\033[94m'+"\t\tEnter the choice of search algorithm: "+"\033[0m"))

            if choice2 == 1:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\dfs1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\dfs2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\dfs3.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 2:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\bfs1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\bfs2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\bfs3.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 3:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\ucs1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\ucs2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\ucs3.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 4:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\best1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\best2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\best3.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\best4.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 5:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\a1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\a2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\a3.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 6:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\g1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\g2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()

            elif choice2 == 7:
                break
            else:
                print("Invalid Choice!!")

        elif choice1 == 2:
            print('\033[92m' + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" + '\033[0m')
            print('\033[92m' + '\033[1m' + "\t\t\t\t\tGame Select Algorithms" + '\033[0m')
            print('\033[92m' + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" + '\033[0m')
            print('\033[92m' +"\tGame Select Algorithms: ")
            print("\t1. Min-Max Algorithm: ")
            print("\t2. Alpha-Beta pruning Algorithm: ")
            print("\t3. Monto Carlo Tree Search: ")
            print("\t4. Exit"+'\033[0m')
            choice2 = int(input('\033[94m'+"\t\tEnter the choice of Game Select algorithm: "+"\033[0m"))

            if choice2 == 1:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\minmax1.png")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\minmax2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 2:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\ab1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\ab2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
            elif choice2 == 3:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\mcts1.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\mcts2.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\mcts3.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\mcts4.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()

            elif choice2 == 4:
                break
            else:
                print("Invalid Choice!!")

        elif choice1 == 3:
            print('\033[93m' + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" + '\033[0m')
            print('\033[93m' + '\033[1m' + "\t\t\t\t\tIntelligent Agents Types" + '\033[0m')
            print('\033[93m' + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" + '\033[0m')
            print('\033[93m'+"\tIntelligent Agents Types: ")
            print("\t1. Simple Reflex agent: ")
            print("\t2. Model-based Reflex Agent: ")
            print("\t3. Goal Based Agent: ")
            print("\t4. Utility Based Agents: ")
            print("\t5. Learning Agent: ")
            print("\t6. Exit"+'\033[0m')
            choice2 = int(input('\033[94m'+"\t\tEnter the choice of Intelligent Agent: "+"\033[0m"))

            if choice2 == 1:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\sra.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 2:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\mbra.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 3:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\gba.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 4:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\uba.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 5:
                image = imread("E:\\Pycharm\\Ai_miniproject\\aiminiproject\\la.jpg")
                plt.imshow(image)
                plt.axis('off')
                plt.show()
                print()
            elif choice2 == 6:
                break
            else:
                print("Invalid Choice!!")
        elif choice1==4:
            break
        else:
            print("Invalid Choice!!")


ai()